// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import ()

type Session struct {
	ID         string `json:"id"`
	SecretHash []byte `json:"secret_hash"`
	CreatedAt  int32  `json:"created_at"`
}
