// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: session.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, secret_hash, created_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	ID         string `json:"id"`
	SecretHash []byte `json:"secret_hash"`
	CreatedAt  int32  `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ID, arg.SecretHash, arg.CreatedAt)
	return err
}
